### ISSUE TITLE
[Bug] Fedora 42 Error Message Keeps Appearing

### ISSUE THREAD

**Issue by gnulab-id** [amir1376/ab-download-manager#891]
### 📝 Description

Hi,

Just installed the app on Fedora 42. I like the appearance alot! But upon the first launch and after every 15-20 seconds, this error message pops up

###### App Info
```
appVersion = 1.7.0
platform = Linux
```
###### Exception
```
java.lang.UnsupportedOperationException: The system tray is not supported on the current platform.
    at java.desktop/java.awt.SystemTray.getSystemTray(Unknown Source)
    at java.desktop/sun.awt.X11.XTrayIconPeer$4$1.run(Unknown Source)
    at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
    at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
    at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
    at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
    at java.base/java.security.AccessController.doPrivileged(Unknown Source)
    at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
    at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
    at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
    at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
    at java.base/java.security.AccessController.doPrivileged(Unknown Source)
    at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
    at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
    at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
    at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
    at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
    at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)

```

### 🏷️ App Version

1.7.0

### 💻 Platform

Fedora 42

### 🔁 Steps to Reproduce

Launch it and the error pops up.

### ✅ Expected Behavior

Such pop up should not appear.

### 📷 Screenshots or Recordings (optional)

<img width="504" height="415" alt="Image" src="https://github.com/user-attachments/assets/9bc497eb-5be8-4698-af80-44e9f31e178d" />

**Comment by makissuelms** [comment]
I'm having the same problem.

**Comment by amir1376** [comment]
please install `libappindocators` and restart the app to see if it solves your problem

**Comment by makissuelms** [comment]
> please install `libappindocators` and restart the app to see if it solves your problem

I did that, but it’s still not working.

<img width="1587" height="874" alt="Image" src="https://github.com/user-attachments/assets/e5ef18f3-e24e-4636-954f-80ce93082299" />

**Comment by amir1376** [comment]
We had a similar issue in our Telegram group, and it was fixed using that solution (maybe you also need to restart your desktop?).

I need to re-implement the system tray feature.
For now, you can disable the system tray in the application settings so it doesn’t bother you until I find a better solution.

**Comment by BISWA63** [comment]
I am on Fedora 43 and this too happens with me, also the system tray icon is bugged

<img width="43" height="31" alt="Image" src="https://github.com/user-attachments/assets/f3e8eb14-c82e-4a0f-b62b-d30374e96b68" />

**Comment by amir1376** [comment]
guys you need to install `libappindocators`

**Comment by BISWA63** [comment]
> guys you need to install `libappindocators`

I did install libappindicator but it did not help at all, instead the system tray icon kept disappearing and reappearing again and again and the error still stayed the same

Edit:
Installation method: installation script
Version: 1.7.1
OS: Fedora Linux 43 Workstation (GNOME)

This error always pops up when the app is not in focus, say I switch to a different app or even open my app list, I cannot quit the app as well so I always have to end app from my task manager

**Comment by amir1376** [comment]
> > guys you need to install `libappindocators`
> 
> I did install libappindicator but it did not help at all, instead the system tray icon kept disappearing and reappearing again and again and the error still stayed the same
> 
> Edit:
> Installation method: installation script
> Version: 1.7.1
> OS: Fedora Linux 43 Workstation (GNOME)
> 
> This error always pops up when the app is not in focus, say I switch to a different app or even open my app list, I cannot quit the app as well so I always have to end app from my task manager


You can also disable system tray for now in the settings.. until I reimplement the system tray

**Comment by eajaykumar** [comment]
same happening with me in latest version 1.8.4 but only when the screen goes off i mean sleep after login i will get this ,am using fedora gnome

**Comment by amir1376** [comment]
Hello everyone 
The logic for the system tray has been updated. Could you please try compiling the master branch on your systems and let me know if the issue is resolved or if you're still encountering related problem?

**Comment by eajaykumar** [comment]
<img width="254" height="187" alt="Image" src="https://github.com/user-attachments/assets/5d409c29-2850-4dd8-a9a2-5e9b7e0297af" />

yea it fixed thank you and tray also got updated
